version: "3"

services:
  db:
    container_name: db
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: delivery-app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-delivery

networks:
  app-delivery:
    driver: bridge
